spring:
  datasource:
    url: jdbc:mysql://doxinets10:3306/prova_liquibase_develop?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
    username: root
    password:
  liquibase:
    change-log: classpath:/db/changelog/changelog-master.mysql.sql